### ISSUE TITLE
ÆØÅ vises forkert efter download

### ISSUE THREAD

**Issue by mortenaag** [Septima/spatialsuite-geomatic-wms#1]
![encoding](https://cloud.githubusercontent.com/assets/11662057/7408576/5c7ffb70-ef1e-11e4-8af1-153f13ae2086.JPG)

efter at have downloadet modulet og pakket det ud er æ å ø blevet lidt spøjse at se på i theme include filen.

Ændrer github på encoding på nogen måde når man bruger "download as zip" funktionen? 

include ser fin ud på selve github når der navigeres til themes.xml

**Comment by rastermanden** [comment]
Jeg undersøger sagen

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk
