### ISSUE TITLE
Nye data fra Geomatic med SLD id'er

### ISSUE THREAD

**Issue by mortenaag** [Septima/spatialsuite-geomatic-wms#35]
Hej alle

jævnfør geomatics nyhedsbrev 15/12-2015 er der kommet nye data i kommunepakken som også skulle være i deres wms og skulle kunne kældes frem med SLD id'er

![udklip](https://cloud.githubusercontent.com/assets/11662057/11862551/a290b95a-a48c-11e5-81cb-30de5a2645e0.PNG)

Jeg har forsøgt at få dem frem ved at bruge samme opbygning som der er i faktor datasources uden held. Er der nogen der kan gennemskue hvordan de fem nye temaer skal hentes ned korrekt?

De eksisterende datasources har id'er på kun 3 cifre.

**Comment by markusroesgen** [comment]
Jeg har prøvet at tilføje den nye variabel ”dagbefolkning” (fem temaer) i vores profil ”geomatic” efter jeres vejledning på Github. Desværre bliver temagruppen ikke synlig i min profil, se vedhæftet beskrivelse.

[Geomatic WMS_dagbefolkning.zip](https://github.com/Septima/spatialsuite-geomatic-wms/files/135910/Geomatic.WMS_dagbefolkning.zip)

**Comment by rastermanden** [comment]
Kan I skaffe et fuldt eksempel på WMS getMap request incl sld paramteren
fra Geomatic

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk

2016-02-18 10:30 GMT+01:00 Markus Rösgen (Sønderborg Kommune) <
notifications@github.com>:

**Comment by markusroesgen** [comment]
Dagbefolkning på WMS
Du kan også se dagbefolkning i dit eget webGIS. For at tilgå disse lag findes følgende ID’er, der skal benyttes til SLD parameter:
• 30909: Dagbefolkning

• 30904: Dagbefolkning i arbejde.

• 30908: Dagbefolkning under uddannelse

• 30905: Dagbefolkning under uddannelse under 15 år

• 30906: Dagbefolkning under uddannelse over 15 år

WMS getMap request har ikke ændret sig, siden I har sat WMS’erne op i jeres Geomatic Public modul – vi har fået rettigheder til at se en ny variabel (dagbefolkning) vi vores kommunepakke.

**Comment by mortenaag** [comment]
De 5 lag fungerer fint her i vores webgis her men vi inkluderer bare alle temagrupper og themes i stedet for at inkludere de enkelte temeagrupper og themes som der står i vejledningen. Da jeg tilføjede temaerne til modulet var jeg ikke opmærksom på at opdatere readme filen.

Der g¨r for øvrigt rygter om at herkomst nu skulle være en del af pakken men jeg har ikke kunne finde en sld id på det.

Fra: Markus Rösgen (Sønderborg Kommune) [mailto:notifications@github.com]
Sendt: 22. februar 2016 10:41
Til: Septima/spatialsuite-geomatic-wms
Cc: Morten Aagaard
Emne: Re: [spatialsuite-geomatic-wms] Nye data fra Geomatic med SLD id'er (#35)

Dagbefolkning på WMS
Du kan også se dagbefolkning i dit eget webGIS. For at tilgå disse lag findes følgende ID’er, der skal benyttes til SLD parameter:
• 30909: Dagbefolkning

• 30904: Dagbefolkning i arbejde.

• 30908: Dagbefolkning under uddannelse

• 30905: Dagbefolkning under uddannelse under 15 år

• 30906: Dagbefolkning under uddannelse over 15 år

WMS getMap request har ikke ændret sig, siden I har sat WMS’erne op i jeres Geomatic Public modul – vi har fået rettigheder til at se en ny variabel (dagbefolkning) vi vores kommunepakke.

**Comment by markusroesgen** [comment]
Hej Morten

Jeg forstår ikke helt hvad du mener. Kan du forklare det lidt nærmere?

Eller sende nogle xml-filer som et eksempel?

På forhånd tak!

Hilsen
Markus

**Comment by mortenaag** [comment]
Hej Markus

Efter download og install af modulet skriver jeg følgende under themegroups i vores profil

`<include mustexist="false" nodes="/profile/themegroups/*" src="[module:spatialsuite-geomatic-wms.dir]/profiles/profile.xml"/>`

og dette under themegroups

`<include mustexist="false" nodes="/profile/themes/*" src="[module:spatialsuite-geomatic-wms.dir]/profiles/profile.xml"/>`

og intet andet, men du har ret i at hvis man ikke vil inkludere ALT så skal man lave den filtrering der står i vejledningen som jeg beklager ieg ikke har opdateret. Jeg er i tvivl om hvordan jeg opdaterer vejledningen men de rettelser du nævnte da du oprettede issuet lyder rigtige

Mvh Morten

**Comment by rastermanden** [comment]
Ma kan rette direkte i Github ved at klikke på readme.md filen og vælge
redigér i øvre højre hjørne

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk

**Comment by markusroesgen** [comment]
Hej Morten

Der mangler noget i din kommentar. HVAD skriver du under themegroups i jeres profil og under themegroups?

Hilsen
Markus

**Comment by mortenaag** [comment]
havde glemt at indsætte det som kode

**Comment by markusroesgen** [comment]
Nu har jeg inkluderet ALT, men temagruppen "dagbefolkning" kommer ikke frem, se skærmdump.

**Comment by markusroesgen** [comment]
Hvorfor får jeg ikke lov til at vedhæfte en fil lige pludseligt?

**Comment by mortenaag** [comment]
[socio.txt](https://github.com/Septima/spatialsuite-geomatic-wms/files/151065/socio.txt)

Jeg har oprettet og tilføjet den ekstra theme include fil til separat include af dagbefolkning og opdateret readme filen. jeg har lige testet det af i vores socio profil med en ny download af modulet og det fungerer her. hvorfor det ikke virker hos dig ved jeg ikke

jeg har vedhæftet vores socio profil som den ser ud lige nu (jeg måtte zippe den da jeg ikek kan direkte uploade xml)

**Comment by markusroesgen** [comment]
Hej Morten

Har du glemt at vedhæfte jeres socio profil-XML eller fik du heller ikke lov til at vedhæfte en fil?

**Comment by mortenaag** [comment]
[socio.txt](https://github.com/Septima/spatialsuite-geomatic-wms/files/151066/socio.txt)

nå, det eneste den vil æde er åbenbart txt

**Comment by markusroesgen** [comment]
Hej Martin

Jeg har gjort præcis som beskrevet, men temagruppen "dagbefolkning" kommer stadig ikke frem. Kan du logge på og finde ud af hvor fejlen ligger?

På forhånd tak for hjælpen.

Hilsen
Markus

**Comment by rastermanden** [comment]
Jeg kigger på det, men når det nok ikke idag.

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk

**Comment by markusroesgen** [comment]
Hej Martin
Hvad er status på opgaven? Jeg håber at du kan fikse det snarest muligt.

**Comment by markusroesgen** [comment]
Hej Morten

Har du lavet en signaturforklaring til klassificeringerne i temagruppen "dagbefolkning", som vi må låne?
Se vedhæftet skærmdump.

Hilsen
Markus

![geomatic_dagbefolkning_signatur](https://cloud.githubusercontent.com/assets/11993556/14348158/f87f3a90-fcba-11e5-944d-b8783a07e122.JPG)

**Comment by mortenaag** [comment]
Nej det har jeg ikke.

Fra: Markus Rösgen (Sønderborg Kommune) [mailto:notifications@github.com]
Sendt: 7. april 2016 12:20
Til: Septima/spatialsuite-geomatic-wms
Cc: Morten Aagaard
Emne: Re: [Septima/spatialsuite-geomatic-wms] Nye data fra Geomatic med SLD id'er (#35)

Hej Morten

Har du lavet en signaturforklaring til klassificeringerne i temagruppen "dagbefolkning", som vi må låne?
Se vedhæftet skærmdump.

Hilsen
Markus

[geomatic_dagbefolkning_signatur]https://cloud.githubusercontent.com/assets/11993556/14348158/f87f3a90-fcba-11e5-944d-b8783a07e122.JPG

**Comment by rastermanden** [comment]
Mon Ikke Geomatic har lavet det i deres WMS server allerede som I kan låne
fra ?

Man kan kalde WMS med "GetLegendGraphics" i stedet for "GetMap" for at få
en signaturforklaring som I kan kopiere.

## 

_Martin Bjærge Jensen_
Partner, konsulent
+45 91326943

## martin@septima.dk klavs@septima.dk

Septima P/S
Frederiksberggade 28 2.tv.
1459 København K

www.septima.dk
